### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [SergeyTsalkov/brooce#1]
First of all, thanks for creating and sharing a nice software!

Could you add LICENSE file?
The following page may help for choosing a license.
[Choose an open source license - Choose a License](http://choosealicense.com/)

I hope you choose a permissive license like MIT or Apache.
Thanks!

**Comment by SergeyTsalkov** [comment]
Thanks for the suggestion about the LICENSE file! This is a new project and I'm still trying to get everything organized! I went with GPLv3 for now, but if you need more permissive licensing for a specific use case you have in mind, feel free to email me and I'm sure we can make it work! My email is listed in my github profile.
