### ISSUE TITLE
Possible unending delay through lock

### ISSUE THREAD

**Issue by MrWook** [SergeyTsalkov/brooce#11]
Maybe I'm missing something but if you add 2 Jobs with a lock on a worker with only one queue. The first one will be executed and the remaining one will be moved to the delay queue (If you don't delete them through the options instead of moving them to the delay queue.)
The default value for the delay queue is 60s. If this first job is done and  a new job arrives with the same lock within the 60s it will be executed. In that way the second job could be stuck in the delay queue forever.
Is this intended or is there a way to move a incoming jobs to the delay queue and execute the jobs from the delay queue first?

**Comment by kjoe** [comment]
In this situation (quickly arriving jobs to the same lock), you could simple use delayed queue to add new jobs, isn't it?

**Comment by MrWook** [comment]
This is what i'm talking about when i said "Maybe I'm missing something" wow I'm stupid. 
I'm sorry that I trashed your issues tab :(
