### ISSUE TITLE
Identifying workers by id

### ISSUE THREAD

**Issue by larslommen** [SergeyTsalkov/brooce#25]
I think I'm missing something? 'server:5' In this example: [Locks That Multiple Jobs Can Hold](https://github.com/SergeyTsalkov/brooce#locks-that-multiple-jobs-can-hold)
Is that the id of a worker you're sending the shell command to? I don't really get how I can send different shell commands to specific workers, for running bash files as example.

**Comment by SergeyTsalkov** [comment]
The lock name is simply a string. A lock called "server:5" is no different than one called "server:xyz". The idea is you restrict which jobs can run simultaneously, so if one job is currently running with the lock "server:5" then other jobs that want the same lock will have to wait.

The only exception is locks that start with a number followed by a colon. The lock "2:server:5" can be held by 2 jobs at the same time.

I don't really know why you'd want the job to be run by a specific worker, but that has nothing to do with locking. If you have multiple machines running jobs, you can have them handle different queues so you can control which jobs go to which machines.

**Comment by larslommen** [comment]
Thanks for clearing that up. So for example, if I have different files on 2 different machines. I should make a queue for machine1 and machine2, so the shell commands get executed on the right machines?

**Comment by SergeyTsalkov** [comment]
That's right-- If a job needs to be run on a particular machine, you should have multiple queues and have each machine work on a different queue.
